-- 表的结构 `ecs_brand`
CREATE TABLE IF NOT EXISTS `ecs_brand` (
  `brand_id` smallint(5) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID号',
  `brand_name` varchar(60) NOT NULL COMMENT '品牌名称',
  `brand_logo` varchar(80) NOT NULL COMMENT '上传的该品牌公司logo图片',
  `brand_desc` text NOT NULL COMMENT '品牌描述',
  `site_url` varchar(255) NOT NULL COMMENT '品牌的网址',
  `sort_order` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '品牌在前台页面的显示顺序，数字越大越靠后',
  `has_show` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '该品牌是否显示，0，否；1，显示',
  PRIMARY KEY (`brand_id`),
  KEY `is_show` (`has_show`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='商品品牌信息记录表' AUTO_INCREMENT=9 ;


-- 表的结构 `ecs_category`
CREATE TABLE IF NOT EXISTS `ecs_category` (
  `cat_id` smallint(5) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID号',
  `cat_name` varchar(90) NOT NULL COMMENT '分类名称',
  `keywords` varchar(255) NOT NULL COMMENT '分类的关键字，可能是为了搜索',
  `cat_desc` varchar(255) NOT NULL COMMENT '分类描述',
  `parent_id` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '该分类的父id，取值于该表的cat_id字段',
  `sort_order` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '该分类在页面显示的顺序，数字越大顺序越靠后；同数字，id在前的先显示',
  `template_file` varchar(50) NOT NULL COMMENT '不确定字段，按名字和表设计猜，应该是该分类的单独模板文件的名字',
  `measure_unit` varchar(15) NOT NULL COMMENT '该分类的计量单位',
  `show_in_nav` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否显示在导航栏，0，不；1，显示在导航栏',
  `style` varchar(150) NOT NULL COMMENT '该分类的单独的样式表的包括文件名部分的文件路径',
  `is_show` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否在前台页面显示，1，显示；0，不显示',
  `grade` tinyint(4) NOT NULL DEFAULT '0' COMMENT '该分类的最高和最低价之间的价格分级，当大于1时，会根据最大最小价格区间分成区间，会在页面显示价格范围，如0-300,300-600,600-900这种',
  `filter_attr` smallint(6) NOT NULL DEFAULT '0' COMMENT '如果该字段有值，则该分类将还会按照该值对应在表goods_attr的goods_attr_id所对应的属性筛选，如，封面颜色下有红，黑分类筛选 ',
  PRIMARY KEY (`cat_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='商品分类表，记录商品分类信息' AUTO_INCREMENT=9 ;


CREATE TABLE IF NOT EXISTS `ecs_goods` (
`goods_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT COMMENT '商品的自增id',
`cat_id` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '商品所属商品分类id，取值ecs_category的cat_id',
`goods_sn` varchar(60) NOT NULL COMMENT '商品的唯一货号',
`goods_name` varchar(120) NOT NULL COMMENT '商品的名称',
`goods_name_style` varchar(60) NOT NULL DEFAULT '+' COMMENT '商品名称显示的样式；包括颜色和字体样式；格式如#ff00ff+strong',
`click_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商品点击数',
`brand_id` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '品牌id，取值于ecs_brand 的brand_id',
`provider_name` varchar(100) NOT NULL COMMENT '供货人的名称，程序还没实现该功能',
`goods_number` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '商品库存数量',
`goods_weight` decimal(10,3) unsigned NOT NULL DEFAULT '0.000' COMMENT '商品的重量，以千克为单位',
`market_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '市场售价',
`shop_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '本店售价',
`promote_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '促销价格',
`promote_start_date` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '促销价格开始日期',
`promote_end_date` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '促销价结束日期',
`warn_number` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '商品报警数量',
`keywords` varchar(255) NOT NULL COMMENT '商品关键字，放在商品页的关键字中，为搜索引擎收录用',
`goods_brief` varchar(255) NOT NULL COMMENT '商品的简短描述',
`goods_desc` text NOT NULL COMMENT '商品的详细描述',
`goods_thumb` varchar(255) NOT NULL COMMENT '商品在前台显示的微缩图片，如在分类筛选时显示的小图片',
`goods_img` varchar(255) NOT NULL COMMENT '商品的实际大小图片，如进入该商品页时介绍商品属性所显示的大图片',
`original_img` varchar(255) NOT NULL COMMENT '应该是上传的商品的原始图片',
`is_real` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '是否是实物，1，是；0，否；比如虚拟卡就为0，不是实物',
`extension_code` varchar(30) NOT NULL COMMENT '商品的扩展属性，比如像虚拟卡',
`is_on_sale` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '该商品是否开放销售，1，是；0，否',
`is_alone_sale` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否能单独销售，1，是；0，否；如果不能单独销售，则只能作为某商品的配件或者赠品销售',
`integral` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '购买该商品可以使用的积分数量，估计应该是用积分代替金额消费；但程序好像还没有实现该功能',
`add_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商品的添加时间',
`sort_order` smallint(4) unsigned NOT NULL DEFAULT '0' COMMENT '应该是商品的显示顺序，不过该版程序中没实现该功能',
`is_delete` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '商品是否已经删除，0，否；1，已删除',
`is_best` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否是精品；0，否；1，是',
`is_new` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否是新品；0，否；1，是',
`is_hot` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否热销，0，否；1，是',
`is_promote` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否特价促销；0，否；1，是',
`bonus_type_id` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '购买该商品所能领到的红包类型',
`last_update` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最近一次更新商品配置的时间',
`goods_type` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '商品所属类型id，取值表goods_type的cat_id',
`seller_note` varchar(255) NOT NULL COMMENT '商品的商家备注，仅商家可见',
`give_integral` int(11) NOT NULL DEFAULT '-1' COMMENT '购买该商品时每笔成功交易赠送的积分数量。',
PRIMARY KEY (`goods_id`),
KEY `goods_sn` (`goods_sn`),
KEY `cat_id` (`cat_id`),
KEY `last_update` (`last_update`),
KEY `brand_id` (`brand_id`),
KEY `goods_weight` (`goods_weight`),
KEY `promote_end_date` (`promote_end_date`),
KEY `promote_start_date` (`promote_start_date`),
KEY `goods_number` (`goods_number`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='商品表' AUTO_INCREMENT=35 ;