spring:
    datasource:
        name: kotlin_mybatis
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/kotlin_mybatis?useUnicode=true&characterEncoding=utf8
        username: root
        password: root

#        druid:
#            initial-size: 30
#            max-active: 100
#            min-idle: 30
#            max-wait: 500
#            defaultAutoCommit: true
#            validation-query: select 1
#            validation-query-timeout: 1
#            test-on-borrow:        false
#            test-on-return:        false
#            test-while-idle:        true
#            time-between-eviction-runs-millis: 60000
#            min-evictable-idle-time-millis:  25200000
#            filters:    stat,slf4j
#            clear-filters-enable: false
#            remove-abandoned: true
#            remove-abandoned-timeout: 1800
#            log-abandoned: true
#            connection-init-sqls: set names utf8mb4

mybatis:
  mapper-locations: "classpath*:/mapper/*Mapper.xml"
  type-aliases-package: com.kotlin.marvel.skm.model
  configuration:
    log-prefix: dao.
    map-underscore-to-camel-case: true
